spring:
  datasource:
    url: jdbc:postgresql://db:5432/${APP_DB_NAME}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.terkep.party/realms/party-map
server:
  forward-headers-strategy: native
  tomcat:
    accesslog:
      enabled: true