### Get all places
GET http://localhost:8080/api/places

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Place by Event
GET http://localhost:8080/api/events/23c3c9fb-23e6-59d7-b317-dd614478e685/place

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Get place's events
GET http://localhost:8080/api/events?placeId=43ce6e13-e30b-5b9f-8cc6-0aa52be7cf85

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Request returns the right events", function () {
        client.assert(jsonPath(response.body, "$[0].id") === "50bf3153-7d1c-51d2-9bb7-cc81432d7311");
        client.assert(jsonPath(response.body, "$[1].id") === "45333217-d63f-5b51-a603-6755d84f914e");
    })
%}